server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://cloki:3100/loki/api/v1/push

scrape_configs:
 - job_name: canary
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      name: loki-canary
      stream: stdout
      __path__: /out/*.log

